using System.Collections.Generic;
using WvsBeta.Game.Scripting;

namespace WvsBeta.Scripts.Scripts
{
    [Script("standard")]
    public class Standard : IStandardScript
    {
        public IDictionary<string, string> ScriptNameMap { get; set; }
        public Standard()
        {
            ScriptNameMap = new Dictionary<string, string>
            {
                { "taxi1", "taxi" },
                { "taxi2", "taxi" },
                { "taxi3", "taxi" },
                { "taxi4", "taxi" },
                { "mTaxi", "taxi" },
                { "market00", "market" },
                { "market01", "market" },
                { "market02", "market" },
                { "market03", "market" },
                { "market04", "market" },
                { "market05", "market" },
                { "market06", "market" },
                { "market07", "market" },
                { "market08", "market" },
                { "market09", "market" },
                { "levelUP", "etc" },
                { "levelUP2", "etc" },
                { "begin2", "mapleIsland" },
                { "begin4", "mapleIsland" },
                { "begin5", "mapleIsland" },
                { "begin7", "mapleIsland" },
                { "bari", "mapleIsland" },
                { "rein", "mapleIsland" },
                { "pio", "mapleIsland" },
                { "rithTeleport", "victoria0" },
                { "jane", "victoria0" },
                { "q2073", "victoria0" },
                { "bush1", "victoria1" },
                { "bush2", "victoria1" },
                { "herb_out", "victoria1" },
                { "herb_in", "victoria1" },
                { "owen", "victoria2" },
                { "mike", "victoria2" },
                { "flower_in", "victoria2" },
                { "viola_pink", "victoria2" },
                { "viola_blue", "victoria2" },
                { "viola_white", "victoria2" },
                { "flower_out", "victoria2" },
                { "petmaster", "victoria2" },
                { "pet_life", "victoria2" },
                { "pet_lifeitem", "victoria2" },
                { "pet_letter", "victoria2" },
                { "subway_ticket", "victoria3" },
                { "_subway_in", "victoria3" },
                { "subway_in", "victoria3" },
                { "subway_get1", "victoria3" },
                { "subway_get2", "victoria3" },
                { "subway_get3", "victoria3" },
                { "subway_out", "victoria3" },
                { "hotel1", "victoria3" },
                { "guild_proc", "ossyria2" },
                { "guild_mark", "ossyria2" },
                { "party1_enter", "party" },
                { "party1_play", "party" },
                { "party1_out", "party" },
                { "refine_henesys", "make1" },
                { "refine_sleepy", "make1" },
                { "face_henesys1", "face" },
                { "face_henesys2", "face" },
                { "face_orbis1", "face" },
                { "face_orbis2", "face" },
                { "face_ludi1", "face" },
                { "face_ludi2", "face" },
                { "lens_henesys1", "face" },
                { "lens_orbis1", "face" },
                { "lens_ludi1", "face" },
                { "skin_henesys1", "skin" },
                { "skin_orbis1", "skin" },
                { "skin_ludi1", "skin" },
                { "hair_henesys1", "hair" },
                { "hair_henesys2", "hair" },
                { "hair_kerning1", "hair" },
                { "hair_kerning2", "hair" },
                { "hair_orbis1", "hair" },
                { "hair_orbis2", "hair" },
                { "hair_ludi1", "hair" },
                { "hair_ludi2", "hair" },
                { "boxPaper0", "zakum" },
                { "boxKey0", "zakum" },
                { "money100", "zakum" },
                { "money10000", "zakum" },
                { "boxItem0", "zakum" },
                { "boxItem1", "zakum" },
                { "boxItem2", "zakum" },
                { "boxItem3", "zakum" },
                { "boxBItem0", "zakum" },
                { "boxMob0", "zakum" },
                { "go280010000", "zakum" },
                { "Zakum00", "zakum" },
                { "Zakum01", "zakum" },
                { "Zakum02", "zakum" },
                { "Zakum03", "zakum" },
                { "Zakum04", "zakum" },
                { "Zakum05", "zakum" },
                { "Zakum06", "zakum" },
                { "boss", "zakum" },
                { "1001000", "shop" },
                { "1001001", "shop" },
                { "1011000", "shop" },
                { "1011001", "shop" },
                { "1011100", "shop" },
                { "1012004", "shop" },
                { "1021000", "shop" },
                { "1021001", "shop" },
                { "1021100", "shop" },
                { "1031000", "shop" },
                { "1031001", "shop" },
                { "1031100", "shop" },
                { "1032103", "shop" },
                { "1052104", "shop" },
                { "1061001", "shop" },
                { "1061002", "shop" },
                { "2012003", "shop" },
                { "2012004", "shop" },
                { "2012005", "shop" },
                { "2020001", "shop" },
                { "2022000", "shop" },
                { "2022001", "shop" },
                { "2022002", "shop" },
                { "2030009", "shop" },
                { "2040049", "shop" },
                { "2041002", "shop" },
                { "2041003", "shop" },
                { "2041006", "shop" },
                { "2041014", "shop" },
                { "2041016", "shop" },
            };
        }
    }
}
